### PR TITLE
fixed file_browser extension

### PR DESCRIPTION
**Pull request by ikerurda**

### CODE REVIEW

**Comment by Conni2461** [comment]
Ups sorry my bad. I went from top to bottom and just merged another PR that has done the same. I am so sorry

**Comment by ikerurda** [comment]
Hi @Conni2461 , could you check this PR?
I actually don't think the merged PR fixes the issue:
```lua
E5108: Error executing lua .../start/telescope.nvim/lua/telescope/_extensions/init.lua:10: 'file_browser' extension doesn't exist or isn't installed: m
odule 'telescope._extensions.file_browser' not found:
        no field package.preload['telescope._extensions.file_browser']
        no file './telescope/_extensions/file_browser.lua'
        no file '/usr/local/Cellar/luajit-openresty/2.1-20220310/share/luajit-2.1.0-beta3/telescope/_extensions/file_browser.lua'
        no file '/usr/local/share/lua/5.1/telescope/_extensions/file_browser.lua'
        no file '/usr/local/share/lua/5.1/telescope/_extensions/file_browser/init.lua'
        no file '/usr/local/Cellar/luajit-openresty/2.1-20220310/share/lua/5.1/telescope/_extensions/file_browser.lua'
        no file '/usr/local/Cellar/luajit-openresty/2.1-20220310/share/lua/5.1/telescope/_extensions/file_browser/init.lua'
        no file '/Users/ikerurda/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/telescope/_extensions/file_browser.lua'
        no file '/Users/ikerurda/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/telescope/_extensions/file_browser/init.lua'
        no file '/Users/ikerurda/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/telescope/_extensions/file_browser.lua'
        no file '/Users/ikerurda/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/telescope/_extensions/file_browser/init.lua'
        no file './telescope/_extensions/file_browser.so'
        no file '/usr/local/lib/lua/5.1/telescope/_extensions/file_browser.so'
        no file '/usr/local/Cellar/luajit-openresty/2.1-20220310/lib/lua/5.1/telescope/_extensions/file_browser.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file '/Users/ikerurda/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/telescope/_extensions/file_browser.so'
        no file './telescope.so'
        no file '/usr/local/lib/lua/5.1/telescope.so'
        no file '/usr/local/Cellar/luajit-openresty/2.1-20220310/lib/lua/5.1/telescope.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file '/Users/ikerurda/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/telescope.so'
stack traceback:
        [C]: in function 'error'
        .../start/telescope.nvim/lua/telescope/_extensions/init.lua:10: in function 'load_extension'
        .../start/telescope.nvim/lua/telescope/_extensions/init.lua:17: in function '__index'
        ...lescope-packer.nvim/lua/telescope/_extensions/packer.lua:108: in function 'key_func'
        ...k/packer/start/telescope.nvim/lua/telescope/mappings.lua:242: in function 'execute_keymap'
        [string ":lua"]:1: in main chunk
```

**Comment by Conni2461** [comment]
You right. I think i rebased your branch correctly and it should be fixed now. Can you validate after that i would merge. I dont use packer. I just look at these repos in the telescope org from time to time (because no one else currently does it)

**Comment by ikerurda** [comment]
Yes, this fixed the issue, thanks!

**Pull request merged**
